### ISSUE TITLE
ERROR models on hunted

### ISSUE THREAD

**Issue by DexterHaslem** [fortressforever/fortressforever#57] opened 2014-11-10 19:54 UTC
saw this last night in a listenserver, wanted to get it down before I forget. 
go to the hatbox / ladder and it will be along the side of the nearest building

**Comment by squeek502** [comment] 2014-11-10 21:49
This is caused by the 'sourcetest' files not being included. Will be fixed on the svn in a bit. Closing preemptively.

**Closed as completed by squeek502** 2014-11-10 21:49 UTC
