### ISSUE TITLE
Flag touch bounds are too small

### ISSUE THREAD

**Issue by rawDawg216** [fortressforever/fortressforever#166] opened 2015-03-29 20:28 UTC
Squeek et al,

Can you please change the vertical flag bounds back to the old values?  I am able to conc right through the flag now and it is beyond frustrating.  Also I am able to jump over the flag without picking it up, when the height of the flag model is clearly higher than the player model can jump.  If the flag bounds will not return to the old ideal values, can you please resize the flag model to reflect the new bounds.  I am sick of people saying, "you shouldn't be able to pick up the flag with your feet."  There is absolutely nothing realistic about the gameplay in Fortress. Stop using that as an argument.  And yes, I should be able to pick up the flag with my feet, especially if I'm flying through the air while crouching from boosting off of a concussion grenade (which if you are looking for realism, is totally fucking preposterous.)

The flag is seriously ruining the gameplay.  Please sir

**Comment by rawDawg216** [comment] 2015-03-30 04:27
Label as bug

**Comment by squeek502** [comment] 2015-03-30 05:47
Not a bug. From the changelog:

> Flag touch bounds have been decreased somewhat significantly: touch height is now ~65% of flag height, and touch width is now ~100% of flag width (flag touch bounds used to be larger than the flag itself in both dimensions)

Some slight tweaks might be made, but need some more time for feedback.

**Comment by AfterShockFF** [comment] 2015-03-30 18:42
**Why was the flag size changed?**

It was changed to encourage more staggered flag progression (concing onto the flag) rather than concing over it and grabbing it from underneath you, and out. The flag height was similarly small in TFC which meant that players conced onto the flag rather than through it, and meant flags moved slower out of the base.

**Why is staggered flag progression a good thing?**
1. **Defending flags in different positions** in your base is more interesting than always defending the exact same position. Having to improvise defensive positions based on where the flag is (and as offense, improvising attack routes and adjusting your concs based on the new/moved defense setup), was one of the really cool parts of TFC. In TFC, it was common to move your sentry gun multiple times as the flag moved out of the base. Soldiers would not have a single position, they would move to cover different positions as the flag travels out of the base. Judging when exactly to move the SG, based on where the flag is, who is dead, who you have defending, etc, was a deep and interesting decision. In TFC players even changed class sometimes based on how far the flag was out of the base. In FF, this didn't exist as much, partially because of how easy a flag was to swoop up, and how quickly after leaving the flag room a flag is captured.
2. **Prevents helplessness** Staggered flag progression prevents the feeling of helplessness a defender feels if he misses 1 shot and suddenly there is a homerun. It can feel overwhelming to defensive players when there are a few homeruns in a row. The urge to quit playing rises dramatically if the flag progression is not staggered. Also, the difference between good defenders and great defenders is increased to a huge amount. If pickup teams are unbalanced, flags can disappear very quickly and repeatedly and there is not much anyone can do to stop it. Slight team balancing problems should not result in double the number of caps than expected.
3. **Homeruns should be rare and exceptional**. In TFC, a homerun was an "awesome" moment - something you would upload as a video, and something that significantly increased your teams chances of winning the game. In FF, homeruns are common. When every player can homerun a flag with a simple single conc it brings the skill ceiling down. We don't see double/triple conc combos as much in FF compared to TFC, because they are simply not required to capture the flag due to the increased ease of touch. In TFC you needed one conc to land on the flag, then another to get out - this hasn't been true in FF. FF would be more interesting and diverse with more combos and exceptional play, and in order to encourage that we need to make it so basic single concs can't homerun the flag so easily.
4. **Pipe trap radius**. The previously large flag grab radius has also meant we've needed to raise the demoman pipe trap radius, just so demoman had a chance of hitting a det against fly-over concs. Whilst this gives more power to the demoman it has also meant that juking pipetraps is harder as the blast radius is larger than TFC. The time a demoman can relay a pipe after missing a det is fast enough that if a medic jukes the pipetrap, a new pipe can be on the flag before he can touch it - so it is nearly always better to either fight the demoman and kill him, or conc straight at the flag and hope to throw the flag before he dets. In general, the more viable choices a player has, the deeper the game, and this is especially true when it comes to psychological battles between players (which bring a great sense of "humanness" and humour to the game).
5. **Conc-choice depth**. Medics have had their depth of choice in conc usage reduced. In TFC, you had to plan when you would use your 2 concs from 4 options:
- Conc midmap
- Conc past front line defender
- Conc to the flag
- Conc away with the flag

Picking 2 from those 4 options gives a lot of variation and depth. If you conced over the midmap, and conced past the first defender, you could not conc at the flag and would need to walk out. Maybe you planned to use a grenade on the front line defender, then conc at the flag. Maybe you'd save both concs for a double conc out with the flag, but you'd need to slowly walk across the midmap, wasting time - a choice not taken lightly, but it could also win games. In FF, if you have a jumppad across the midmap, that removes the need for 1 conc. If you can conc in and out with the flag with the same conc, that removes another. So the choice is reduced - you can use 1 conc for the front line and 1 for the flag. The only choice remaining is whether to prime a conc or a frag nade (which is still an interesting and deep choice, just not as interesting as before).

6 . **Variation in flag defense classes**. Having a large flag radius means that soldiers (and HWs) defending the flag aren't as viable. In TFC, soldiers defending the flag were common. In FF it is a little difficult, in part because of the flag radius. Whilst it is true that the demoman is "at home" defending the flag, and can't really hold a front line position, (and thus it makes sense he is "best" at defending the flag) we should also consider what happens when a soldier must cover the flag when the demoman dies - having a dead demoman should not mean that the flag flies straight out of the base and everyone resets. A soldier should be able to cover for a demoman more than is currently possible - A demoman should expect to return to a new position after his flag moved a reasonable distance, rather than return to the flag room having the flag completely gone.

**Summary**

There are other reasons, such as increased importance on conc numbers between medic/scout, tactically placing flags on ramps, inability for engineers to reset easily, increasing body blocking, AvD capture times.. but the above are the main ones. The change will require a slight shift in how offense is played. Offense will need to work harder to homerun the flag now, and some old moves will no longer work - this is deliberate and intended. 

All that said, the exact size may not be perfect. We may be able to alter the radius slightly provided the above points are still addressed. Ideally we'd like players to get used to the changes first, then decide if the radius needs changing once things have settled down.

**Comment by Rawretta** [comment] 2015-03-31 05:28
I have noticed a big change in the flag that's for sure. I've conc'd directly into it and never picked it up, I've jumped over it somehow, but know that my character has clipped through it, but no pickup at all. I agree with rawdawg and maybe the flag needs some tweaking. I'm not saying to go back to what it was, but maybe work a tad on the height and so on and see what might work a little better. It has been a very frustrating issue with offense for me. 

-LadyDeath

**Comment by DexterHaslem** [comment] 2015-03-31 05:44
I can double that notion, as a casual pubber this change has been surprisingly noticeable. I cant drive by HH w/ solly on AVD maps, which I guess is the intention. but sometimes It's flying right near center of the flag, so I'd suggest + 15%~20% flag bbounds height  (from what it currently is, not old values). Definitely not as tall as it was before , because that was too tall, but maybe a tad higher so it isnt fuck-you-into-outerspace?

**Comment by ProjectMoon** [comment] 2015-03-31 11:31
It should be increased enough that it's not possible to jump over the flag, or apparently conc through it.

**Comment by BBEEAANN** [comment] 2015-04-02 08:10
The flag height and width need tweaking. Defensive players can stand on the flag and hinder the offense from touching it. It is one thing to block a player from the flag, but standing a HW on it removes the ability to grab it. This is true with dispensers and SG building as well. Please increase the height and width slightly so this cannot happen. I understand the need to slow the game down for the new players, but making it so they can't cap a flag is not helping them play o. Balance is needed, not a see saw from an already o oriented game to a d oriented slugfest.

**Comment by AirTrek** [comment] 2015-04-08 12:49
I like the smaller flag a lot - more of a challenge to snag it and funner to defend. I do agree with some people that the bounds aren't perfect and may need to be tweaked.

**Comment by squeek502** [comment] 2015-04-12 01:57
Here's a poll to gather some more specific feedback:

http://strawpoll.me/4103407

Feel free to send it around; the more votes, the better.

**Comment by AfterShockFF** [comment] 2016-05-31 18:19
Closing since we increased the bounds again

**Closed as completed by AfterShockFF** 2016-05-31 18:19 UTC
Labels: design/balance
