### ISSUE TITLE
Spy weapons show on three classes

### ISSUE THREAD

**Issue by ndo360** [fortressforever/fortressforever#239] opened 2015-08-07 06:25 UTC
If a spy is disguised as either a Medic, Heavy, or Pyro with his/her tranquilizer equipped, then everyone can see it is a tranquilizer and not the weapon the hud displays. (The weapon the hud displays is a crowbar.)

**Comment by squeek502** [comment] 2015-08-07 06:41
Duplicate of https://github.com/fortressforever/fortressforever/issues/178, which has been fixed in code and should have been fixed in the last update, but something seems to have gone wrong with that.

Need to push a new build to Steam, probably. I think the build @alaswell pushed missed some commits or wasn't fully up to date, as it's also been noted that https://github.com/fortressforever/fortressforever/pull/195 is missing from the current build even though it should have been included.

**Closed as completed by squeek502** 2015-08-07 06:41 UTC
