### ISSUE TITLE
Flag to Small/Short

### ISSUE THREAD

**Issue by BBEEAANN** [fortressforever/fortressforever#183] opened 2015-04-01 23:18 UTC
The flag height and width need tweaking. Defensive players can stand on the flag and hinder the offense from touching it. It is one thing to block a player from the flag, but standing a HW on it removes the ability to grab it. This is true with dispensers and SG building as well. Please increase the height and width slightly so this cannot happen. I understand the need to slow the game down for the new players, but making it so they can't cap a flag is not helping them play o. Balance is needed, not a see saw from an already o oriented game to a d oriented slugfest.

**Comment by squeek502** [comment] 2015-04-01 23:51
Duplicate of #166

**Closed as completed by squeek502** 2015-04-01 23:51 UTC
